"""FIX

Revision ID: 1fd9d5461b4a
Revises: 756bb42fb73f
Create Date: 2023-08-31 16:51:29.834020

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1fd9d5461b4a'
down_revision: Union[str, None] = '756bb42fb73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__chats__settings_id__settings', 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('fk__chats__settings_id__settings'), 'chats', 'settings', ['settings_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk__companies__struct_id__structs', 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('fk__companies__struct_id__structs'), 'companies', 'structs', ['struct_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk__companies__struct_id__structs'), 'companies', type_='foreignkey')
    op.create_foreign_key('fk__companies__struct_id__structs', 'companies', 'structs', ['struct_id'], ['id'])
    op.drop_constraint(op.f('fk__chats__settings_id__settings'), 'chats', type_='foreignkey')
    op.create_foreign_key('fk__chats__settings_id__settings', 'chats', 'settings', ['settings_id'], ['id'])
    # ### end Alembic commands ###
