"""Initial

Revision ID: 7f83b7a3fa46
Revises: 
Create Date: 2023-08-26 01:09:47.438076

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f83b7a3fa46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('city', sa.String(), nullable=True)
    )
    op.create_index(op.f('ix__settings__city'), 'settings', ['city'], unique=False)
    op.create_index(op.f('ix__settings__id'), 'settings', ['id'], unique=False)
    op.create_table('structs',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('events_path', sa.String(), nullable=False),
    sa.Column('title_path', sa.String(), nullable=False),
    sa.Column('date_path', sa.String(), nullable=False),
    sa.Column('city_path', sa.String(), nullable=True),
    sa.Column('preview_path_link', sa.String(), nullable=True),
    sa.Column('page_link_path', sa.String(), nullable=True)
    )
    op.create_index(op.f('ix__structs__id'), 'structs', ['id'], unique=False)
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('is_notify', sa.Boolean(), nullable=False),
    sa.Column('settings_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], name=op.f('fk__chats__settings_id__settings')),
    sa.PrimaryKeyConstraint('chat_id', 'settings_id', name=op.f('pk__chats'))
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('struct_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['struct_id'], ['structs.id'], name=op.f('fk__companies__struct_id__structs')),
    sa.PrimaryKeyConstraint('struct_id', name=op.f('pk__companies'))
    )
    op.create_index(op.f('ix__companies__id'), 'companies', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('preview_link', sa.String(), nullable=True),
    sa.Column('page_link', sa.String(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk__events__company_id__companies')),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk__events'))
    )
    op.create_index(op.f('ix__events__city'), 'events', ['city'], unique=False)
    op.create_index(op.f('ix__events__id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix__events__title'), 'events', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__events__title'), table_name='events')
    op.drop_index(op.f('ix__events__id'), table_name='events')
    op.drop_index(op.f('ix__events__city'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix__companies__id'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('chats')
    op.drop_index(op.f('ix__structs__id'), table_name='structs')
    op.drop_table('structs')
    op.drop_index(op.f('ix__settings__id'), table_name='settings')
    op.drop_index(op.f('ix__settings__city'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
