version: "3.8"

services:
  redis:
    container_name: "redis"
    image: redis:7.2.4
    restart: always
    command:
      - 'redis-server'
      - '--requirepass $${REDIS_PASSWORD}'
      - '--save 60 20'
      - '--maxmemory 300mb'
    ports:
      -  "6379:6379"
    env_file:
      - .env
    volumes:
      - redis-data:/data

volumes:
  redis-data: